<?php

// お知らせ
const UI_ITEM_NOTICE = "お知らせ★";
const UI_ITEM_NOTICE_TITLE = "タイトル★";
const UI_ITEM_NOTICE_CONTENT = "内容★";
const UI_ITEM_NOTICE_CREATE_DATE = "作成日★";
const UI_ITEM_NOTICE_UPDATE_DATE = "更新日★";

// ユーザー
const UI_ITEM_USER = "ユーザー★";
const UI_ITEM_USER_ID = "ユーザーID★";
const UI_ITEM_USER_NAME = "ユーザー名★";
const UI_ITEM_USER_PASSWORD = "パスワード★";
const UI_ITEM_USER_PERMISSION = "権限★";
const UI_ITEM_USER_APPROVAL = "承認★";
const UI_ITEM_USER_DELETED = "削除★";
const UI_ITEM_USER_CREATE_DATE = "作成日★";
const UI_ITEM_USER_UPDATE_DATE = "更新日★";
const UI_ITEM_USER_APPROVAL_DATE = "承認日★";
const UI_ITEM_USER_DELETED_DATE = "削除日★";

// ユーザー設定
const UI_ITEM_USER_SETTING_KEY = "キー★";
const UI_ITEM_USER_SETTING_VALUE = "値★";

// 所属グループ
const UI_ITEM_GROUP = "所属グループ★";
const UI_ITEM_GROUPS_ID = "所属グループID★";
const UI_ITEM_GROUP_NAME = "所属グループ名★";
const UI_ITEM_GROUP_PASSWORD = "パスワード★";

// 所属グループ情報
const UI_ITEM_GROUP_INFO = "所属グループ情報★";
const UI_ITEM_GROUP_INFO_LEADER = "ユーザー種別★";
const UI_ITEM_GROUP_INFO_APPROVAL = "所属グループ承認★";
const UI_ITEM_GROUP_INFO_CREATE_DATE = "作成日★";
const UI_ITEM_GROUP_INFO_UPDATE_DATE = "更新日★";

// 所属グループ設定
const UI_ITEM_GROUP_SETTING_KEY = "キー★";
const UI_ITEM_GROUP_SETTING_VALUE = "値★";

// 購入者
const UI_ITEM_MEMBER = "購入者★";
const UI_ITEM_MEMBER_NO = "No★";
const UI_ITEM_MEMBER_NAME = "購入者名★";
const UI_ITEM_MEMBER_STATUS = "ステータス★";

// カテゴリー
const UI_ITEM_CATEGORY = "カテゴリー★";
const UI_ITEM_CATEGORY_NO = "No★";
const UI_ITEM_CATEGORY_NAME = "カテゴリー名★";
const UI_ITEM_CATEGORY_STATUS = "ステータス★";

// 購入データ
const UI_ITEM_SHOPPING = "購入データ★";
const UI_ITEM_SHOPPING_USER = "登録ユーザー★";
const UI_ITEM_SHOPPING_MEMBER = UI_ITEM_MEMBER_NAME;
const UI_ITEM_SHOPPING_CATEGORY = UI_ITEM_CATEGORY_NAME;
const UI_ITEM_SHOPPING_DATE = "購入日★";
const UI_ITEM_SHOPPING_TYPE = "種別★";
const UI_ITEM_SHOPPING_PAYMENT = "支払い★";
const UI_ITEM_SHOPPING_SETTLEMENT = "精算★";
const UI_ITEM_SHOPPING_AMOUNT = "金額★";
const UI_ITEM_SHOPPING_REMARKS = "備考★";
const UI_ITEM_SHOPPING_REPLACE = "置換★";

// コメント
const UI_ITEM_COMMENT = "コメント★";
const UI_ITEM_COMMENT_CONTENT = "備考★";

// 確定データ
const UI_ITEM_FIXED = "確定データ★";
const UI_ITEM_FIXED_FLG = "確定★";

// 予算
const UI_ITEM_BUDGETS = "予算★";
const UI_ITEM_BUDGETS_NO = "No★";
const UI_ITEM_BUDGETS_CATEGORY = UI_ITEM_CATEGORY_NAME;
const UI_ITEM_BUDGETS_AMOUNT = "予算金額★";

// 登録テンプレート
const UI_ITEM_ENTRY_TEMPLATE = "登録テンプレート★";
const UI_ITEM_ENTRY_TEMPLATE_NO = "No★";
const UI_ITEM_ENTRY_TEMPLATE_ID = "ID★";
const UI_ITEM_ENTRY_TEMPLATE_NAME = "登録テンプレート名★";
const UI_ITEM_ENTRY_TEMPLATE_MEMBER = UI_ITEM_SHOPPING_MEMBER;
const UI_ITEM_ENTRY_TEMPLATE_CATEGORY = UI_ITEM_SHOPPING_CATEGORY;
const UI_ITEM_ENTRY_TEMPLATE_TYPE = UI_ITEM_SHOPPING_TYPE;
const UI_ITEM_ENTRY_TEMPLATE_PAYMENT = UI_ITEM_SHOPPING_PAYMENT;
const UI_ITEM_ENTRY_TEMPLATE_SETTLEMENT = UI_ITEM_SHOPPING_SETTLEMENT;
const UI_ITEM_ENTRY_TEMPLATE_AMOUNT = UI_ITEM_SHOPPING_AMOUNT;
const UI_ITEM_ENTRY_TEMPLATE_REMARKS = UI_ITEM_SHOPPING_REMARKS;
const UI_ITEM_ENTRY_TEMPLATE_USE = "使用状況★";
const UI_ITEM_ENTRY_TEMPLATE_STATUS = "ステータス★";

// 入力テンプレート
const UI_ITEM_INPUT_TEMPLATE = "入力テンプレート★";
const UI_ITEM_INPUT_TEMPLATE_NO = "No★";
const UI_ITEM_INPUT_TEMPLATE_ID = "ID★";
const UI_ITEM_INPUT_TEMPLATE_NAME = "入力テンプレート名★";
const UI_ITEM_INPUT_TEMPLATE_MEMBER = UI_ITEM_SHOPPING_MEMBER;
const UI_ITEM_INPUT_TEMPLATE_CATEGORY = UI_ITEM_SHOPPING_CATEGORY;
const UI_ITEM_INPUT_TEMPLATE_TYPE = UI_ITEM_SHOPPING_TYPE;
const UI_ITEM_INPUT_TEMPLATE_PAYMENT = UI_ITEM_SHOPPING_PAYMENT;
const UI_ITEM_INPUT_TEMPLATE_SETTLEMENT = UI_ITEM_SHOPPING_SETTLEMENT;
const UI_ITEM_INPUT_TEMPLATE_AMOUNT = UI_ITEM_SHOPPING_AMOUNT;
const UI_ITEM_INPUT_TEMPLATE_REMARKS = UI_ITEM_SHOPPING_REMARKS;
const UI_ITEM_INPUT_TEMPLATE_USE = "使用★";
const UI_ITEM_INPUT_TEMPLATE_STATUS = "ステータス★";

// 検索テンプレート
const UI_ITEM_SEARCH_TEMPLATE = "検索テンプレート★";
const UI_ITEM_SEARCH_TEMPLATE_NO = "No★";
const UI_ITEM_SEARCH_TEMPLATE_ID = "ID★";
const UI_ITEM_SEARCH_TEMPLATE_NAME = "検索テンプレート名★";
const UI_ITEM_SEARCH_TEMPLATE_MEMBER = UI_ITEM_SHOPPING_MEMBER;
const UI_ITEM_SEARCH_TEMPLATE_CATEGORY = UI_ITEM_SHOPPING_CATEGORY;
const UI_ITEM_SEARCH_TEMPLATE_TYPE = UI_ITEM_SHOPPING_TYPE;
const UI_ITEM_SEARCH_TEMPLATE_PAYMENT = UI_ITEM_SHOPPING_PAYMENT;
const UI_ITEM_SEARCH_TEMPLATE_SETTLEMENT = UI_ITEM_SHOPPING_SETTLEMENT;
const UI_ITEM_SEARCH_TEMPLATE_MIN_AMOUNT = "最小金額★";
const UI_ITEM_SEARCH_TEMPLATE_MAX_AMOUNT = "最大金額★";
const UI_ITEM_SEARCH_TEMPLATE_REMARKS = UI_ITEM_SHOPPING_REMARKS;
const UI_ITEM_SEARCH_TEMPLATE_USE = "使用★";
const UI_ITEM_SEARCH_TEMPLATE_STATUS = "ステータス★";

const UI_ITEM_LABEL_NULL = "__Null__★";
const UI_ITEM_LABEL_ALL = "すべて★";
